version: "3.7"

services:
  maxdb:
    image: "ibmcom/db2:11.5.7.0a"
    hostname: "${ENV_MAXDB_SERVICE_HOST}"
    environment:
      - "LICENSE=accept"
      - "DB2INSTANCE=ctginst1"
      - "DB2INST1_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "DBNAME=MAXDB76"
    networks:
      - backend
     ports:
       - "${ENV_MAXDB_SERVICE_PORT}:${ENV_MAXDB_SERVICE_PORT}"
    volumes:
      - type: volume
        source: maxdb76
        target: /home/ctginst1/ctginst1
      # - type: bind
      #   source: ./backup
      #   target: /backup
