version: "3.7"

services:
  maxdb:
    image: oracle/database:18.4.0-xe
    hostname: "${ENV_MAXDB_SERVICE_HOST}"
    shm_size: 1G
    environment:
      - "ORACLE_PWD=${ENV_DB_MAXIMO_PASSWORD}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "ORACLE_CHARACTERSET=AL32UTF8"
    networks:
      - backend
    ports:
      - "${ENV_ORACLE_DB_PORT}:${ENV_ORACLE_DB_PORT}"
      - 5500:5500
      - 8080:8080
    volumes:
      - type: bind
        source: ./oracle
        target: /opt/oracle/scripts/setup

  maximo:
    image: "${ENV_NAMESPACE}/maximo:${ENV_MAXIMO_VER}"
    environment:
      - DB_VENDOR=Oracle
      - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
      - "MXE_DB_FORMAT_NULLVALUE=NVL"
      - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
      - "MXINTADM_PASSWORD=${ENV_MXINTADM_PASSWORD}"
      - "MAXADMIN_PASSWORD=${ENV_MAXADMIN_PASSWORD}"
      - "MAXREG_PASSWORD=${ENV_MAXREG_PASSWORD}"
      - "MAXDB=${ENV_ORACLE_DB_INSTANCE}"
      - "DB_TABLE_SPACE=MAXDATA"
      - "DB_TEMP_SPACE=MAXTEMP"
      - "DB_INDEX_SPACE=MAXDATA"
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - UPDATE_APPS_ON_REBOOT=yes
      - KEEP_RUNNING=yes
      - "BASE_LANG=${ENV_BASE_LANG}"
      - "ADD_LANGS=${ENV_ADD_LANGS}"
      - "ADMIN_EMAIL_ADDRESS=${ENV_ADMIN_EMAIL_ADDRESS}"
      - "SMTP_SERVER_HOST_NAME=${ENV_SMTP_SERVER_HOST_NAME}"
      - "SKIN=${ENV_SKIN}"
      - "ENABLE_DEMO_DATA=${ENV_ENABLE_DEMO_DATA}"
    depends_on:
      - maxdb
    networks:
      - backend
    volumes:
      - maximo:/maximo

  maximo-ui:
    image: "${ENV_NAMESPACE}/maximo-ui:${ENV_MAXIMO_VER}"
    environment:
      - DB_VENDOR=Oracle
      - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
      - "MXE_DB_FORMAT_NULLVALUE=NVL"
      - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - GEN_MAXIMO_PROPERTIES=no
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
      - "LDAP_PORT=${ENV_LDAP_PORT}"
      - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
      - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
      - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
      - "LICENSE=accept"
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "WLP_LOGGING_CONSOLE_LOGLEVEL=info"
      - "WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc,audit"
      - "WLP_DEBUG_SUSPEND=n"
      - "MXE_CRONTASK_DONOTRUN=ALL"
    #ports:
    #  - "9080:9080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maximo-ui.entrypoints=web"
      - "traefik.http.routers.maximo-ui.service=maximo-ui"
      - "traefik.http.routers.maximo-ui.rule=PathPrefix(`/maximo`) || PathPrefix(`/maximo-x`)"
      - "traefik.http.services.maximo-ui.loadbalancer.server.port=9080"
      - "traefik.http.services.maximo-ui.loadbalancer.sticky=true"
      - "traefik.http.services.maximo-ui.loadbalancer.sticky.cookie.name=StickyCookie"
      - "traefik.http.services.maximo-ui.loadbalancer.sticky.cookie.secure=true"
    depends_on:
      - maxdb
      - jmsserver
    networks:
      frontend:
        aliases:
          - maximo-ui
      backend:
    volumes:
      - maximo:/maximo

  maximo-cron:
    image: "${ENV_NAMESPACE}/maximo-cron:${ENV_MAXIMO_VER}"
    environment:
      - DB_VENDOR=Oracle
      - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
      - "MXE_DB_FORMAT_NULLVALUE=NVL"
      - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - GEN_MAXIMO_PROPERTIES=no
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
      - "LDAP_PORT=${ENV_LDAP_PORT}"
      - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
      - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
      - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "WLP_DEBUG_SUSPEND=n"
    depends_on:
      - maxdb
      - jmsserver
    networks:
      frontend:
      backend:
    volumes:
      - maximo:/maximo

  # maximo-api:
  #   image: "${ENV_NAMESPACE}/maximo-api:${ENV_MAXIMO_VER}"
  #   environment:
  #     - DB_VENDOR=Oracle
  #     - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
  #     - "MXE_DB_FORMAT_NULLVALUE=NVL"
  #     - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
  #     - "LDAP_PORT=${ENV_LDAP_PORT}"
  #     - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
  #     - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
  #     - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   #ports:
  #   #  - "9081:9081"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.maximo-api.entrypoints=web"
  #     - "traefik.http.routers.maximo-api.service=maximo-api"
  #     - "traefik.http.routers.maximo-api.rule=PathPrefix(`/maximoapi`)"
  #     - "traefik.http.services.maximo-api.loadbalancer.server.port=9081"
  #     - "traefik.http.services.maximo-api.loadbalancer.sticky=true"
  #     - "traefik.http.services.maximo-api.loadbalancer.sticky.cookie.name=StickyCookie"
  #     - "traefik.http.services.maximo-api.loadbalancer.sticky.cookie.secure=true"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-api
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-report:
  #   image: "${ENV_NAMESPACE}/maximo-report:${ENV_MAXIMO_VER}"
  #   environment:
  #     - DB_VENDOR=Oracle
  #     - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
  #     - "MXE_DB_FORMAT_NULLVALUE=NVL"
  #     - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
  #     - "LDAP_PORT=${ENV_LDAP_PORT}"
  #     - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
  #     - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
  #     - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   #ports:
  #   #  - "9082:9082"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.maximo-report.entrypoints=web"
  #     - "traefik.http.routers.maximo-report.service=maximo-report"
  #     - "traefik.http.routers.maximo-report.rule=PathPrefix(`/maximoreport`)"
  #     - "traefik.http.services.maximo-report.loadbalancer.server.port=9082"
  #     - "traefik.http.services.maximo-report.loadbalancer.sticky=true"
  #     - "traefik.http.services.maximo-report.loadbalancer.sticky.cookie.name=StickyCookie"
  #     - "traefik.http.services.maximo-report.loadbalancer.sticky.cookie.secure=true"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-report
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-mea:
  #   image: "${ENV_NAMESPACE}/maximo-mea:${ENV_MAXIMO_VER}"
  #   environment:
  #     - DB_VENDOR=Oracle
  #     - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
  #     - "MXE_DB_FORMAT_NULLVALUE=NVL"
  #     - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
  #     - "LDAP_PORT=${ENV_LDAP_PORT}"
  #     - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
  #     - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
  #     - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #     - "WLP_DEBUG_SUSPEND=n"
  #   #ports:
  #   #  - "9084:9084"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.maximo-mea.entrypoints=web"
  #     - "traefik.http.routers.maximo-mea.service=maximo-meaweb"
  #     - "traefik.http.routers.maximo-mea.rule=PathPrefix(`/meaweb`)"
  #     - "traefik.http.services.maximo-mea.loadbalancer.server.port=9084"
  #     - "traefik.http.services.maximo-mea.loadbalancer.sticky=true"
  #     - "traefik.http.services.maximo-mea.loadbalancer.sticky.cookie.name=StickyCookie"
  #     - "traefik.http.services.maximo-mea.loadbalancer.sticky.cookie.secure=true"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-mea
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-jmsconsumer:
  #   image: "${ENV_NAMESPACE}/maximo-jmsconsumer:${ENV_MAXIMO_VER}"
  #   environment:
  #     - DB_VENDOR=Oracle
  #     - "MXE_DB_DRIVER=oracle.jdbc.OracleDriver"
  #     - "MXE_DB_FORMAT_NULLVALUE=NVL"
  #     - "MXE_DB_SYSTEMDATEFORMAT=sysdate"
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - "LDAP_HOST_NAME=${ENV_LDAP_HOST_NAME}"
  #     - "LDAP_PORT=${ENV_LDAP_PORT}"
  #     - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
  #     - "LDAP_BIND_DN=${ENV_LDAP_BIND_DN}"
  #     - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   #ports:
  #   #  - "9083:9083"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.maximo-jmsconsumer.entrypoints=web"
  #     - "traefik.http.routers.maximo-jmsconsumer.service=maximo-jmsconsumer"
  #     - "traefik.http.routers.maximo-jmsconsumer.rule=PathPrefix(`/maximojmsconsumer`)"
  #     - "traefik.http.services.maximo-jmsconsumer.loadbalancer.server.port=9083"
  #     - "traefik.http.services.maximo-jmsconsumer.loadbalancer.sticky=true"
  #     - "traefik.http.services.maximo-jmsconsumer.loadbalancer.sticky.cookie.name=StickyCookie"
  #     - "traefik.http.services.maximo-jmsconsumer.loadbalancer.sticky.cookie.secure=true"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-jmsconsumer
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  jmsserver:
    image: "${ENV_NAMESPACE}/jmsserver:${ENV_WAS_VER}"
    environment:
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "MAXIMO_JMS_SERVICE_SSL_PORT=${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    hostname: "${ENV_MAXIMO_JMS_SERVICE_HOST}"
    # ports:
    #   - "${ENV_MAXIMO_JMS_SERVICE_PORT}:${ENV_MAXIMO_JMS_SERVICE_PORT}"
    #   - "${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}:${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    networks:
      - frontend

  frontend-proxy:
    image: traefik:v2.4.8 # The official v2 Traefik docker image
    ports:
      - "80:80"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend
      - backend

  # ldap:
  #   image: osixia/openldap:1.5.0
  #   hostname: "${ENV_LDAP_HOST_NAME}"
  #   command: --loglevel debug
  #   environment:
  #     - LDAP_LOG_LEVEL=256
  #     - "LDAP_ORGANISATION=${ENV_LDAP_ORGANIZATION}"
  #     - "LDAP_DOMAIN=${ENV_LDAP_DOMAIN}"
  #     # - "LDAP_BASE_DN=${ENV_LDAP_BASE_DN}"
  #     # - "LDAP_ADMIN_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - "LDAP_CONFIG_PASSWORD=${ENV_LDAP_CONFIG_PASSWORD}"
  #     - LDAP_READONLY_USER=true
  #     - "LDAP_READONLY_USER_USERNAME=${ENV_LDAP_USER_NAME}"
  #     - "LDAP_READONLY_USER_PASSWORD=${ENV_LDAP_ADMIN_PASSWORD}"
  #     - LDAP_RFC2307BIS_SCHEMA=false
  #     - LDAP_BACKEND=mdb
  #     - LDAP_TLS=false
  #     - LDAP_REPLICATION=false
  #     - KEEP_EXISTING_CONFIG=false
  #     - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
  #   volumes:
  #     - /var/lib/ldap
  #     - /etc/ldap/slapd.d
  #     - /container/service/slapd/assets/certs/
  #     - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
  #   networks:
  #     - backend
  #   #ports:
  #   #  - "${ENV_LDAP_PORT}:${ENV_LDAP_PORT}"

networks:
  frontend:
  backend:
volumes:
  maxdb76:
  # Shared directory for liberty deployment files
  maximo:
